### ISSUE TITLE
No bootable device when finished Part-1

### ISSUE THREAD

**Issue by gcd0318** [AdhamNasr/MacBookAir-ArchLinux-i3#1]
Hi,

I followed the steps until the last step of Part-1, but after remove USB disk dnd reboot, my MBA-13 (2015 early) failed boot, and indicating no bootable device

Could anyone give some suggestions? Thanks in advance

**Comment by AdhamNasr** [comment]
Try holding the option key as soon as you switch the macbook on, if there are no options, then something went wrong during your setup, either the bootloader isn't installed right, or the partitioning and encryption are done wrong.

**Comment by AdhamNasr** [comment]
@gcd0318 I just updated the guide.

Let me know how it works for you :)
