### ISSUE TITLE
missed reflector in step 9 of Part-1

### ISSUE THREAD

**Issue by gcd0318** [AdhamNasr/MacBookAir-ArchLinux-i3#2]
pacstrap /mnt base base-devel syslinux nano linux-zen linux-zen-headers linux-firmware mkinitcpio lvm2 networkmanager network-manager-applet dialog acpi acpi_call acpid intel-ucode openssh os-prober **reflector**

**Comment by AdhamNasr** [comment]
It comes in part 2.

**Comment by gcd0318** [comment]
> It comes in part 2.

exactly it is included in Part-2, but reflector service is enabled in Part-1. Maybe move this step to Part-2? Just a reminder
:-)

**Comment by AdhamNasr** [comment]
ahh you mean the timer systemctl... hmm, just noticed that, my bad, thanks for letting me know.

Anyway, as I mentioned, I have a newer guide, will try to finalise it and upload by the end of the week.
