### ISSUE TITLE
Doesn't work with apple's proprietary wifi card

### ISSUE THREAD

**Issue by JackStormSword** [AdhamNasr/MacBookAir-ArchLinux-i3#5]
Doesn't work with apple's proprietary wifi card, doesn't even let you get past 1st step of installation. Requires 3rd party BCM4360 firmware to work and no way to install it

**Comment by AdhamNasr** [comment]
if you read the install guide properly, you'll notice that in [part 3](https://github.com/AdhamNasr/MacBookAir-ArchLinux-i3/blob/main/Install-p3.md) I explain how to install the WiFi driver.

Doing the initial installation of the Arch system on Apple devices over WiFi is a hassle, I would recommend installing with a lan cable 1st.

**Comment by JackStormSword** [comment]
> if you read the install guide properly, you'll notice that in [part 3](https://github.com/AdhamNasr/MacBookAir-ArchLinux-i3/blob/main/Install-p3.md) I explain how to install the WiFi driver.
> 
> Doing the initial installation of the Arch system on Apple devices over WiFi is a hassle, I would recommend installing with a lan cable 1st.

Yes I've read that, I also read entire arch and debian wiki and none of them have a solution. Macbook air doesn't have an ethernet port so I can't install it with a lan cable and proprietary wifi card doesn't recognize any drivers that I feed it and I also tried different usb wifi adapters and none of them work.
